accounts/urls.py
from django.urls import path

from . import views


app_name = 'accounts'
urlpatterns = [
    path('register/', views.RegisterUser.as_view(), name="register-user"),
    path('login/', views.LoginUser.as_view(), name="login-user"),
    path('logout/', views.LogoutUser.as_view(), name="logout-user"),
    path('delete/<int:pk>', views.DeleteUser.as_view(), name="delete-user"),
    
]

defaultDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('update/<int:pk>', views.UpdateView.as_view(), name="update-post"),
    path('delete/<int:pk>', views.DeletePost.as_view(), name="delete-post"),
]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models

from django.contrib.auth.models import User
# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField(max_length=500)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title

posts/forms.py
from django.forms import ModelForm
from .models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        exclude = ['author',]
 

accounts/views.py
from django.urls import reverse 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import DeleteView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.



class RegisterUser(CreateView):
    form_class = UserCreationForm
    template_name = 'accounts/register.html'
    
    def get_success_url(self):
        return reverse('posts:index')
    

    

    
    
class LoginUser(LoginView):
    template_name = 'accounts/login.html'


class LogoutUser(LogoutView, LoginRequiredMixin):
    template_name = 'posts/index.html'


class DeleteUser(DeleteView, LoginRequiredMixin):
    model = User
    template_name = 'accounts/confirm.html'
    def get_success_url(self):
        return reverse('posts:index')

posts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse

from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, UpdateView, DeleteView
from django.views.generic.edit import FormMixin
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Post
from .forms import PostForm
# Create your views here.



class IndexView(LoginRequiredMixin, ListView, FormMixin):
    model = Post
    form_class = PostForm
    template_name = 'posts/index.html'
    def get(self, request, *args, **kwargs):
        self.object = None
        self.form = self.get_form(self.form_class)
        
        return ListView.get(self, request, *args, **kwargs)
        
    def post(self, request, *args, **kwargs):
        self.object = None
        self.form = self.get_form(self.form_class)
        
        if self.form.is_valid():
            self.new_post = self.form.save(commit=False)
            self.author = self.request.user
            self.new_post.author = self.author
            self.new_post.save()
            
        return self.get(request, *args, **kwargs)
        
        
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['form'] = PostForm()
        context['posts'] = Post.objects.all().order_by('-date_posted')
        return context



class UpdatePost(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/update.html'
    fields = ['content',]


class DeletePost(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = None
    
    def get_success_url(self):
        return reverse('posts:index')
    
    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

    
    
    
    
    
    
    
    
    
    
    

accounts/templates/accounts/confirm.html
{% extends 'posts/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Confirm{% endblock%}

{% block content %}

<div class="container">
	<div class="col-md-6 mx-auto">
		<form method="POST">
			{% csrf_token %}
			<p>Are you sure?</p> 
				<input type="submit" class="btn btn-danger col-md-4" value="Yes, delete">
				<a class="btn btn-info" href="{% url 'posts:index' %}">No, take me back</a>
		</form>
		
	</div>
</div>











{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'posts/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock%}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
			<div class="card card-signin my-5">
				<div class="card-body">
					<h5 class="card-title text-center">Login</h5>
					<form class="form-signin" method="POST">
						{% csrf_token %}
						<div class="form-label-group my-5">
							<input type="text" id="inputUsername" name="username" class="form-control" placeholder="Username" required autofocus>
						</div>

						<div class="form-label-group my-5">
							<input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required>
						</div>
				
						<button class="btn btn-md btn-primary btn-block" type="submit">Login</button>
						<button class="btn btn-md btn-success btn-block" href="{% url 'accounts:register-user' %}">Create an account</a></button>
						{% if messages %}
							<hr class="my-4">
							<ul class="messages" style="list-style: none">
								{% for message in messages %}
									<li class="alert alert-danger">{{ message }}</li>
								{% endfor %}
							</ul>
						{% endif %}
					</form>
				</div>
			</div>
		</div>
    </div>
	
</div>
{% endblock content %}

accounts/templates/accounts/register.html
{% extends 'posts/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Register{% endblock%}

{% block content %}
<div class="container">
	<div class="form-group col-md-6 my-20 mx-auto border p-4">
		<form method="POST">
			{% csrf_token %}
			
			{{ form | crispy }}
			
			<input class="btn btn-success" value="Register" type="submit">
			<a class="btn btn-info" href="{% url 'accounts:login-user' %}">I already have an account</a>
			
		</form>
	</div>
</div>
{% endblock content %}

posts/templates/posts/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
	</head>
	
	
	<body>
		{% include 'posts/navbar.html' %}
		{% block content %}
		
		{% endblock %}
		
		

		<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
	</body>
</html>

posts/templates/posts/index.html
{% extends 'posts/base.html' %}
{% load crispy_forms_tags %}


{% block title %}Homepage{% endblock%}


{% block content %}
<div class="container">
	<div class="col-md-5 mx-auto mb-5">
		{% if user.is_authenticated %}
		<button class="btn btn-primary offset-5" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
			New Post
			</button>

		<div class="collapse mb-5" id="collapseExample">

			<form method="POST" class="mx-auto">
				{% csrf_token %}
				
				{{ form | crispy }}
				<button class="btn btn-success offset-5" type="submit">Post</button>
			</form>
		</div>
		
	</div>

	<div class="col-md-10 mx-auto p-2 border">
		{% for post in posts %}
		<div class="col-md-12 mx-auto">
			<div class="row p-2">
				<div class="col">
					<h4>{{ post.title }}</h5>
				</div>
				<div class="col-align-self-end">
					<h5>by: {{ post.author }}</h5>
				</div>
			</div>
			<div class=".text-break my-10 border p-5 text-wrap" style="word-wrap:break-word;">
				<p>{{ post.content }}</p>
			</div>
			<div class="row border-bottom border-dark p-2">
				<small class="mx-auto">posted {{ post.date_posted}}</small>
			</div>
			{% if request.user == post.author%}
			<div class="row m-1">
				<a class="btn btn-warning" href="{% url 'posts:update-post' post.pk %}">Update Post</a>
				<a class="btn btn-danger offset-8" href="{% url 'posts:delete-post' post.pk %}">Delete Post</a>
			{% endif %}
			</div>
		</div>
		<br><br>
		{% endfor %}


{% else %}
	<div class="col-md-6 mx-auto">
	<p>You must be logged in to view content of this site</p> 
		<a class="btn btn-success" href="{% url 'accounts:register-user' %}">Register</a>

		<a class="btn btn-info" href="{% url 'accounts:login-user' %}">Login</a>	
	</div>
{% endif %}
</div>
</div>
{% endblock content %}

posts/templates/posts/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
		<a class="navbar-brand" href="https://github.com/Nowikens" target="_blank" >Nowikens</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	  
	<div class="collapse navbar-collapse" id="navbarNav">
		<ul class="navbar-nav">
			<li class="nav-item active">
				<a class="nav-link" href="{% url 'posts:index' %}">Home Page</a>
			</li>
			
			{% if not user.is_authenticated %}
			<li class="nav-item">	
				<a class="nav-link" href="{% url 'accounts:register-user' %}">Register</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'accounts:login-user' %}">Login</a>	
			</li>
			{% endif %}
			
			{% if user.is_authenticated %}
			
				<li class="nav-item">
					<a class="nav-link" href="{% url 'accounts:logout-user' %}">Logout</a>
				</li>
				<li class="nav-item">	
					<a method="POST" class="nav-link" href="{% url 'accounts:delete-user' request.user.pk %}">Delete account</a>
				</li>
				<li class="text-right">
				<span class="navbar-text">{{ request.user }}</span>
				</li>
			
			{% endif %}
		</ul>
	</div>
</nav>

posts/templates/posts/update.html
{% extends 'posts/base.html' %}
{% load crispy_forms_tags %}


{% block title %}Update Post{% endblock%}


{% block content %}

<div class="container">
	<div class="form-group col-md-6 my-20 mx-auto border p-4">
		<form method="POST">
			{% csrf_token %}
			{{ form | crispy }}
			
			<input class="btn btn-success" value="Update" type="submit">
			<a class="btn btn-warning" href="{% url 'posts:index' %}">Cancel</a>
			
		</form>
	</div>
</div>
{% endblock content %}